'use strict';
const $=id=>document.getElementById(id);
const canvas=$('battleCanvas'),ctx=canvas.getContext('2d');
const ATTRS={none:{name:'無',icon:'○'},fire:{name:'火',icon:'🔥'},wood:{name:'木',icon:'🌳'},earth:{name:'土',icon:'🪨'},lightning:{name:'雷',icon:'⚡'},water:{name:'水',icon:'💧'}};
const ADV={fire:'wood',wood:'earth',earth:'lightning',lightning:'water',water:'fire'};
const ROLE_COLORS={tank:'#5ba5ff',special:'#ff735f',assassin:'#b47cff',archer:'#64dc96',knight:'#ffd065',ranger:'#4fd8e8',support:'#ff8bc2'};
const UNITS={
 shield:{name:'盾兵',role:'タンク',roleKey:'tank',lane:'front',count:2,hp:210,atk:15,range:28,speed:20,rate:1.15,art:'shield'},
 golem:{name:'ゴーレム',role:'タンク',roleKey:'tank',lane:'front',count:1,hp:390,atk:29,range:31,speed:11,rate:1.7,art:'golem'},
 knight:{name:'ナイト',role:'ナイト',roleKey:'knight',lane:'mid',count:2,hp:145,atk:36,range:31,speed:28,rate:.95,art:'knight'},
 wolf:{name:'ウルフ',role:'ナイト',roleKey:'knight',lane:'mid',count:3,hp:78,atk:23,range:25,speed:44,rate:.72,art:'wolf'},
 assassin:{name:'アサシン',role:'アサシン',roleKey:'assassin',lane:'mid',count:1,hp:86,atk:68,range:25,speed:51,rate:1.05,art:'assassin',backline:true},
 archer:{name:'アーチャー',role:'アーチャー',roleKey:'archer',lane:'back',count:2,hp:70,atk:30,range:132,speed:19,rate:1.13,art:'archer',projectile:true},
 ranger:{name:'レンジャー',role:'レンジャー',roleKey:'ranger',lane:'back',count:2,hp:80,atk:23,range:112,speed:24,rate:.82,art:'ranger',projectile:true},
 priest:{name:'神官',role:'サポーター',roleKey:'support',lane:'back',count:1,hp:95,atk:9,range:105,speed:18,rate:1.65,art:'priest',heal:true},
 bomber:{name:'爆弾兵',role:'特攻',roleKey:'special',lane:'front',count:3,hp:44,atk:108,range:18,speed:58,rate:99,art:'bomber',bomb:true}
};
const unitCards=Object.keys(UNITS).map(id=>({id:'u_'+id,type:'unit',unit:id,name:UNITS[id].name,tag:UNITS[id].role,desc:`${UNITS[id].count}体召喚`,art:UNITS[id].art}));
const buffs=[
 {id:'b_hp',type:'buff',name:'鉄壁訓練',tag:'強化',desc:'全ユニット耐久 +15%',stat:'hp',value:.15,art:'heart'},
 {id:'b_atk',type:'buff',name:'猛攻訓練',tag:'強化',desc:'全ユニット攻撃 +15%',stat:'atk',value:.15,art:'sword'},
 {id:'b_spd',type:'buff',name:'迅速訓練',tag:'強化',desc:'攻撃間隔 -12%',stat:'rate',value:.12,art:'speed'},
 {id:'b_bomb',type:'buff',name:'大型火薬',tag:'特攻強化',desc:'爆発威力 +35%',stat:'bomb',value:.35,art:'bomb'}
];
const attrCards=Object.keys(ATTRS).map(k=>({id:'a_'+k,type:'attr',attr:k,name:'属性カード（？）',tag:'属性（？）',desc:'ラウンド開始時に公開',art:'mysteryAttr'}));
const rares=[
 {id:'r_life',type:'rare',name:'レアカード（？）',tag:'レア（？）',desc:'ラウンド開始時に開封',effect:'life',art:'mysteryRare'},
 {id:'r_swap',type:'rare',name:'レアカード（？）',tag:'レア（？）',desc:'ラウンド開始時に開封',effect:'swap',art:'mysteryRare'},
 {id:'r_blank',type:'rare',name:'レアカード（？）',tag:'レア（？）',desc:'ラウンド開始時に開封',effect:'blank',art:'mysteryRare'}
];
let state;
function freshPlayer(){return {life:5,attr:'none',army:[],buff:{hp:0,atk:0,rate:0,bomb:0},rare:[],pendingAttr:[],summons:[]}}
function fresh(){return {round:1,you:freshPlayer(),npc:freshPlayer(),loser:null,pick:0,picksNeeded:3,rerolled:false,timeLeft:30,timer:null,npcPlan:[],npcRevealIndex:0,phase:'draft',previewUnits:[],summonFx:[],battle:null};}
function init(){state=fresh();$('gameOverView').classList.add('hidden');$('draftPanel').classList.remove('hidden');$('resultPanel').classList.add('hidden');nextDraft();}
function hearts(n){return '♥'.repeat(Math.max(0,n))+'♡'.repeat(Math.max(0,5-n));}
function updateHud(hidden=true){$('youLife').textContent=hearts(state.you.life);$('npcLife').textContent=hearts(state.npc.life);$('roundNo').textContent=state.round;$('youAttr').textContent=hidden?'？？？':ATTRS[state.you.attr].icon+ATTRS[state.you.attr].name;$('npcAttr').textContent=hidden?'？？？':ATTRS[state.npc.attr].icon+ATTRS[state.npc.attr].name;}
function weightedCard(round){const r=Math.random();if(r<.01)return rares[Math.floor(Math.random()*rares.length)];if(r<.05)return attrCards[Math.floor(Math.random()*attrCards.length)];const pool=round===1?unitCards:[...unitCards,...buffs];return pool[Math.floor(Math.random()*pool.length)];}
function offers(){const arr=[];while(arr.length<3){const c=weightedCard(state.round);if(!arr.some(x=>x.id===c.id))arr.push(c)}return arr;}
function nextDraft(){clearInterval(state.timer);state.phase='draft';state.pick=0;state.picksNeeded=state.loser==='you'?4:3;state.rerolled=false;state.npcRevealIndex=0;state.npcPlan=[];for(let i=0;i<(state.loser==='npc'?4:3);i++)state.npcPlan.push(chooseNpc(offers()));$('phase').textContent='ドラフト';$('draftPanel').classList.remove('hidden');$('resultPanel').classList.add('hidden');$('rerollBtn').classList.remove('hidden');updateHud(true);rebuildPreview();renderOffers(offers());startTimer();drawScene();}
function startTimer(){clearInterval(state.timer);state.timeLeft=30;$('timer').textContent='30';state.timer=setInterval(()=>{state.timeLeft--;$('timer').textContent=state.timeLeft;if(state.timeLeft<=0){clearInterval(state.timer);const cards=[...document.querySelectorAll('.card')];if(cards.length)cards[Math.floor(Math.random()*cards.length)].click();}},1000)}
function renderOffers(os){const root=$('cards');root.innerHTML='';$('draftTitle').textContent=`カード選択 ${state.pick+1}/${state.picksNeeded}`;$('draftHelp').textContent='選ぶと戦場へ召喚・待機します';os.forEach(c=>{const b=document.createElement('button');b.className=`card ${c.type}`;b.innerHTML=`<span class="tag">${c.tag}</span><div class="card-art">${cardArtSvg(c)}</div><h3>${c.name}</h3><p>${c.desc}</p>`;b.onclick=()=>pick(c);root.appendChild(b)});$('pickProgress').style.setProperty('--progress',`${state.pick/state.picksNeeded*100}%`)}
function pick(c){clearInterval(state.timer);applyCard(state.you,c,'you');revealNpcStep();state.pick++;$('pickProgress').style.setProperty('--progress',`${state.pick/state.picksNeeded*100}%`);if(state.pick>=state.picksNeeded){$('rerollBtn').classList.add('hidden');setTimeout(beginRound,650);return}renderOffers(offers());startTimer();}
function applyCard(p,c,side){if(c.type==='unit'){p.army.push(c.unit);summonUnitPreview(side,c.unit)}else if(c.type==='buff'){p.buff[c.stat]+=c.value;showBanner(`${side==='you'?'YOU':'NPC'}：${c.name}`,500)}else if(c.type==='attr'){p.pendingAttr.push(c.attr);summonHiddenToken(side,'attr')}else if(c.type==='rare'){p.rare.push(c.effect);summonHiddenToken(side,'rare')}}
function revealNpcStep(){const c=state.npcPlan[state.npcRevealIndex++];if(c)applyCard(state.npc,c,'npc')}
function chooseNpc(os){return [...os].sort((a,b)=>scoreNpc(b)-scoreNpc(a))[0]}
function scoreNpc(c){if(c.type==='rare')return 85;if(c.type==='unit'){let s=52;if(state.npc.army.length<3)s+=22;if(['shield','golem'].includes(c.unit))s+=8;if(c.unit==='bomber')s+=6;return s+Math.random()*10}if(c.type==='buff')return state.npc.army.length?57+Math.random()*12:13;if(c.type==='attr')return 40+Math.random()*17;return 20}
$('rerollBtn').onclick=()=>{if(state.rerolled)return;state.rerolled=true;$('rerollBtn').classList.add('hidden');renderOffers(offers());startTimer()};
function rebuildPreview(){state.previewUnits=[];for(const side of ['npc','you'])for(const id of state[side].army)addPreviewUnits(side,id,false);}
function summonUnitPreview(side,id){addPreviewUnits(side,id,true)}
function addPreviewUnits(side,id,animate){const t=UNITS[id],existing=state.previewUnits.filter(u=>u.side===side&&u.lane===t.lane).length;for(let i=0;i<t.count;i++){const idx=existing+i,pos=previewPosition(side,t.lane,idx);const u={side,type:id,lane:t.lane,x:pos.x,y:pos.y,scale:animate?0.05:1,alpha:animate?0:1,bounce:0};state.previewUnits.push(u);if(animate)state.summonFx.push({unit:u,t:0})}}
function summonHiddenToken(side,kind){const y=side==='you'?575:65,x=kind==='attr'?65:355;state.summonFx.push({token:true,side,kind,x,y,t:0})}
function previewPosition(side,lane,index){const laneY=side==='you'?{front:455,mid:515,back:570}:{front:185,mid:125,back:70};const cols=6;return {x:50+(index%cols)*64+(Math.floor(index/cols)%2)*16,y:laneY[lane]+Math.floor(index/cols)*(side==='you'?25:-25)}}
async function beginRound(){clearInterval(state.timer);$('draftPanel').classList.add('hidden');state.phase='reveal';$('phase').textContent='開封';await revealPending('npc');await revealPending('you');$('phase').textContent='属性公開';updateHud(false);showBanner(`${ATTRS[state.npc.attr].icon} NPC　VS　YOU ${ATTRS[state.you.attr].icon}`,900);await wait(1000);startBattle();}
async function revealPending(side){const p=state[side];while(p.pendingAttr.length){const attr=p.pendingAttr.shift();await revealCard('attribute','属性カード開封',`${side==='you'?'YOU':'NPC'}：${ATTRS[attr].icon} ${ATTRS[attr].name}属性`);p.attr=attr;updateHud(true)}while(p.rare.length){const effect=p.rare.shift();let text='';if(effect==='life'){p.life++;text=`${side==='you'?'YOU':'NPC'}：ライフ +1`;updateHud(true)}else if(effect==='swap'){const other=side==='you'?'npc':'you';if(p.army.length&&state[other].army.length){const a=Math.floor(Math.random()*p.army.length),b=Math.floor(Math.random()*state[other].army.length);[p.army[a],state[other].army[b]]=[state[other].army[b],p.army[a]];text='両軍のユニットが1体入れ替わった';rebuildPreview()}else text='入れ替えるユニットがいなかった'}else text='……何も起こらなかった';await revealCard('rare','レアカード開封',text)}}
async function revealCard(kind,title,result){$('revealCard').className='reveal-card '+(kind==='attribute'?'attribute':'');$('revealSeal').textContent='?';$('revealTitle').textContent=title;$('revealResult').textContent='';$('revealOverlay').classList.remove('hidden');await wait(480);$('revealSeal').textContent=kind==='attribute'?'✦':'★';$('revealResult').textContent=result;await wait(1000);$('revealOverlay').classList.add('hidden')}
function startBattle(){state.phase='battle';$('phase').textContent='戦闘';state.battle={units:[...makeFighters('npc'),...makeFighters('you')],projectiles:[],effects:[],last:performance.now(),done:false,lastDamageSide:null};requestAnimationFrame(loop)}
function makeFighters(side){const p=state[side],arr=[],laneCount={front:0,mid:0,back:0};for(const id of p.army){const t=UNITS[id];for(let i=0;i<t.count;i++){const idx=laneCount[t.lane]++,pos=previewPosition(side,t.lane,idx);arr.push({side,type:id,lane:t.lane,x:pos.x,y:pos.y,vx:0,vy:0,hp:t.hp*(1+p.buff.hp),maxHp:t.hp*(1+p.buff.hp),atk:t.atk*(1+p.buff.atk),range:t.range,speed:t.speed,rate:Math.max(.32,t.rate*(1-p.buff.rate)),cool:Math.random()*.5,alive:true,target:null,backline:t.backline,heal:t.heal,bomb:t.bomb,bombMult:1+p.buff.bomb,anim:Math.random()*6.28,hit:0,attack:0})}}return arr}
function loop(now){if(!state.battle||state.battle.done)return;const dt=Math.min(.034,(now-state.battle.last)/1000);state.battle.last=now;updateBattle(dt);drawScene();if(!state.battle.done)requestAnimationFrame(loop)}
function attrMult(a,b){if(ADV[a]===b)return 1.25;if(ADV[b]===a)return .8;return 1}
function nearest(u,foes){let list=foes;if(u.backline){const back=foes.filter(f=>f.lane==='back');if(back.length)list=back}let best=null,dist=1e9;for(const e of list){const d=Math.hypot(e.x-u.x,e.y-u.y);if(d<dist){dist=d;best=e}}return best}
function damage(att,target,amount){target.hp-=amount*attrMult(state[att.side].attr,state[target.side].attr);target.hit=.14;state.battle.lastDamageSide=att.side;if(target.hp<=0){target.alive=false;state.battle.effects.push({kind:'poof',x:target.x,y:target.y,t:0});if(target.bomb)explode(target)}}
function explode(u){state.battle.effects.push({kind:'boom',x:u.x,y:u.y,t:0});for(const e of state.battle.units.filter(v=>v.alive&&v.side!==u.side&&Math.hypot(v.x-u.x,v.y-u.y)<92))damage(u,e,u.atk*u.bombMult)}
function updateBattle(dt){const units=state.battle.units;for(const u of units){if(!u.alive)continue;u.cool-=dt;u.hit=Math.max(0,u.hit-dt);u.attack=Math.max(0,u.attack-dt);u.anim+=dt*5;const foes=units.filter(v=>v.alive&&v.side!==u.side);if(!foes.length){finishBattle(u.side);return}if(u.heal&&u.cool<=0){const allies=units.filter(v=>v.alive&&v.side===u.side&&v.hp<v.maxHp);if(allies.length){const a=allies.sort((x,y)=>x.hp/x.maxHp-y.hp/y.maxHp)[0];a.hp=Math.min(a.maxHp,a.hp+24);state.battle.effects.push({kind:'heal',x:a.x,y:a.y,t:0});u.cool=u.rate;u.attack=.25;continue}}
 if(!u.target||!u.target.alive)u.target=nearest(u,foes);const t=u.target;if(!t)continue;const dx=t.x-u.x,dy=t.y-u.y,d=Math.hypot(dx,dy)||1;if(d<=u.range){u.vx*=.65;u.vy*=.65;if(u.cool<=0){u.attack=.22;if(u.bomb){u.alive=false;explode(u)}else if(UNITS[u.type].projectile){state.battle.projectiles.push({side:u.side,x:u.x,y:u.y,target:t,damage:u.atk,t:0});}else damage(u,t,u.atk);u.cool=u.rate}}else{let desired=u.speed;if(u.lane==='back'&&d<72)desired=-u.speed*.75;const tx=dx/d*desired,ty=dy/d*desired;u.vx+=(tx-u.vx)*Math.min(1,dt*6);u.vy+=(ty-u.vy)*Math.min(1,dt*6);u.x+=u.vx*dt;u.y+=u.vy*dt;u.x=Math.max(28,Math.min(392,u.x));u.y=Math.max(30,Math.min(610,u.y))}}
 for(const p of state.battle.projectiles){if(!p.target.alive){p.dead=true;continue}p.t+=dt*5;const dx=p.target.x-p.x,dy=p.target.y-p.y,d=Math.hypot(dx,dy)||1;p.x+=dx/d*170*dt;p.y+=dy/d*170*dt;if(d<12){const fake={side:p.side};damage(fake,p.target,p.damage);p.dead=true}}
 state.battle.projectiles=state.battle.projectiles.filter(p=>!p.dead);for(const e of state.battle.effects)e.t+=dt;state.battle.effects=state.battle.effects.filter(e=>e.t<.75)}
function finishBattle(winner){if(state.battle.done)return;state.battle.done=true;const loser=winner==='you'?'npc':'you';state[loser].life--;state.loser=loser;updateHud(false);$('resultText').textContent=`${winner==='you'?'YOU':'NPC'} ラウンド勝利`;$('resultPanel').classList.remove('hidden');if(state[loser].life<=0)setTimeout(()=>gameOver(winner),650)}
function drawScene(){drawField();if(state.phase==='battle'&&state.battle)drawBattleUnits();else drawPreviewUnits();drawTokens();drawFx()}
function drawField(){ctx.clearRect(0,0,420,640);const g=ctx.createLinearGradient(0,0,0,640);g.addColorStop(0,'#83bd5b');g.addColorStop(.5,'#9bd56e');g.addColorStop(1,'#7fbd59');ctx.fillStyle=g;ctx.fillRect(0,0,420,640);ctx.fillStyle='#b7e58d';ctx.beginPath();ctx.moveTo(20,320);ctx.lineTo(400,245);ctx.lineTo(400,395);ctx.lineTo(20,470);ctx.closePath();ctx.fill();ctx.strokeStyle='#6aa44e55';ctx.lineWidth=2;for(let y=75;y<610;y+=70){ctx.beginPath();ctx.moveTo(10,y);ctx.lineTo(410,y-42);ctx.stroke()}for(let x=35;x<420;x+=70){ctx.beginPath();ctx.moveTo(x,30);ctx.lineTo(x-45,610);ctx.stroke()}drawScenery()}
function drawScenery(){const spots=[[25,95,'tree'],[390,130,'tree'],[28,520,'rock'],[387,555,'tree'],[70,300,'flower'],[350,330,'flower'],[185,35,'rock'],[240,603,'flower']];for(const [x,y,k] of spots){if(k==='tree'){ctx.fillStyle='#60442e';ctx.fillRect(x-3,y,6,14);ctx.fillStyle='#3c8f46';ctx.beginPath();ctx.arc(x,y-3,13,0,6.28);ctx.fill()}else if(k==='rock'){ctx.fillStyle='#71806f';ctx.beginPath();ctx.ellipse(x,y,10,6,-.2,0,6.28);ctx.fill()}else{ctx.fillStyle='#fff59b';for(let a=0;a<5;a++){ctx.beginPath();ctx.arc(x+Math.cos(a*1.256)*4,y+Math.sin(a*1.256)*4,2,0,6.28);ctx.fill()}}}}
function drawPreviewUnits(){for(const fx of state.summonFx){if(fx.unit){fx.t+=.07;fx.unit.scale=Math.min(1,fx.t*1.6);fx.unit.alpha=Math.min(1,fx.t*2);fx.unit.bounce=Math.sin(Math.min(1,fx.t)*Math.PI)*18}else if(fx.token)fx.t+=.07}state.summonFx=state.summonFx.filter(f=>f.t<1.1);for(const u of state.previewUnits){ctx.save();ctx.globalAlpha=u.alpha;drawChibi(u.x,u.y-u.bounce,u.type,u.side,0,false,Math.sin(performance.now()/300+u.x)*.04,u.scale);ctx.restore()}requestAnimationFrame(()=>{if(state.phase==='draft')drawScene()})}
function drawTokens(){const tokenTypes={you:{attr:state.you.pendingAttr.length,rare:state.you.rare.length},npc:{attr:state.npc.pendingAttr.length,rare:state.npc.rare.length}};for(const side of ['npc','you']){const y=side==='you'?595:45;if(tokenTypes[side].attr)drawHiddenToken(48,y,'属性',tokenTypes[side].attr,'#ffd25d');if(tokenTypes[side].rare)drawHiddenToken(372,y,'レア',tokenTypes[side].rare,'#cf69ff')}}
function drawHiddenToken(x,y,label,count,color){ctx.save();ctx.translate(x,y);ctx.fillStyle='#1b2134dd';ctx.strokeStyle=color;ctx.lineWidth=2;roundRect(-28,-17,56,34,9);ctx.fill();ctx.stroke();ctx.fillStyle=color;ctx.font='bold 11px sans-serif';ctx.textAlign='center';ctx.fillText(`${label}(?)`,0,-1);ctx.font='bold 10px sans-serif';ctx.fillText(`×${count}`,0,12);ctx.restore()}
function drawBattleUnits(){for(const p of state.battle.projectiles){ctx.fillStyle=p.side==='you'?'#e9f9ff':'#ffe2e8';ctx.beginPath();ctx.arc(p.x,p.y,4,0,6.28);ctx.fill()}const alive=state.battle.units.filter(u=>u.alive).sort((a,b)=>a.y-b.y);for(const u of alive)drawChibi(u.x,u.y,u.type,u.side,u.attack,u.hit>0,u.anim,1);}
function drawFx(){if(!state.battle)return;for(const e of state.battle.effects){const q=e.t/.75;if(e.kind==='boom'){ctx.save();ctx.globalAlpha=1-q;ctx.fillStyle='#ffcf47';ctx.beginPath();ctx.arc(e.x,e.y,18+q*65,0,6.28);ctx.fill();ctx.fillStyle='#ff714f';ctx.beginPath();ctx.arc(e.x,e.y,10+q*38,0,6.28);ctx.fill();ctx.restore()}else if(e.kind==='poof'){ctx.save();ctx.globalAlpha=1-q;ctx.fillStyle='#f4f0df';for(let i=0;i<6;i++){ctx.beginPath();ctx.arc(e.x+Math.cos(i)*q*25,e.y+Math.sin(i)*q*18,7*(1-q),0,6.28);ctx.fill()}ctx.restore()}else if(e.kind==='heal'){ctx.save();ctx.globalAlpha=1-q;ctx.fillStyle='#72ff9e';ctx.font='bold 24px sans-serif';ctx.textAlign='center';ctx.fillText('✚',e.x,e.y-q*35);ctx.restore()}}}
function drawChibi(x,y,type,side,attack,hit,anim,scale=1){const t=UNITS[type];ctx.save();ctx.translate(x,y);ctx.scale(scale,scale);const facing=side==='you'?-1:1;ctx.scale(1,facing);const bob=Math.sin(anim)*1.6;ctx.translate(0,bob);ctx.fillStyle='#0004';ctx.beginPath();ctx.ellipse(0,11,15,6,0,0,6.28);ctx.fill();if(hit)ctx.globalAlpha=.55;const skin='#ffd3ae',body=ROLE_COLORS[t.roleKey];ctx.fillStyle=body;ctx.beginPath();ctx.ellipse(0,2,11,13,0,0,6.28);ctx.fill();ctx.fillStyle=skin;ctx.beginPath();ctx.arc(0,-13,11,0,6.28);ctx.fill();drawFace();ctx.save();ctx.translate(0,attack?Math.sin((.22-attack)/.22*Math.PI)*7:0);drawEquipment(type);ctx.restore();ctx.restore();
 function drawFace(){ctx.fillStyle='#2a2a35';ctx.beginPath();ctx.arc(-4,-14,1.4,0,6.28);ctx.arc(4,-14,1.4,0,6.28);ctx.fill()}
 function drawEquipment(k){ctx.lineWidth=3;ctx.strokeStyle='#2a2e39';ctx.fillStyle='#eef3ff';if(k==='shield'){ctx.fillStyle='#6389c9';ctx.beginPath();ctx.roundRect(-16,-4,12,20,4);ctx.fill();ctx.stroke();ctx.strokeStyle='#d7e7ff';ctx.beginPath();ctx.moveTo(8,-5);ctx.lineTo(15,13);ctx.stroke()}else if(k==='golem'){ctx.fillStyle='#77857a';ctx.beginPath();ctx.arc(0,-13,13,0,6.28);ctx.fill();ctx.fillRect(-16,-1,8,20);ctx.fillRect(8,-1,8,20)}else if(k==='knight'){ctx.fillStyle='#d7e6f2';ctx.beginPath();ctx.arc(0,-13,12,0,6.28);ctx.fill();ctx.strokeStyle='#f4d06f';ctx.beginPath();ctx.moveTo(7,-5);ctx.lineTo(16,15);ctx.stroke()}else if(k==='wolf'){ctx.fillStyle='#58606b';ctx.beginPath();ctx.ellipse(0,0,16,10,0,0,6.28);ctx.fill();ctx.beginPath();ctx.arc(0,-11,10,0,6.28);ctx.fill();ctx.beginPath();ctx.moveTo(-8,-17);ctx.lineTo(-6,-27);ctx.lineTo(-1,-18);ctx.moveTo(8,-17);ctx.lineTo(6,-27);ctx.lineTo(1,-18);ctx.fill()}else if(k==='assassin'){ctx.fillStyle='#332542';ctx.beginPath();ctx.moveTo(0,-28);ctx.lineTo(14,-5);ctx.lineTo(-14,-5);ctx.closePath();ctx.fill();ctx.strokeStyle='#f4f4ff';ctx.beginPath();ctx.moveTo(-13,7);ctx.lineTo(13,-7);ctx.stroke()}else if(k==='archer'){ctx.strokeStyle='#704c27';ctx.beginPath();ctx.arc(10,2,13,-1.5,1.5);ctx.stroke();ctx.beginPath();ctx.moveTo(10,-11);ctx.lineTo(10,15);ctx.stroke()}else if(k==='ranger'){ctx.fillStyle='#4f7650';ctx.beginPath();ctx.moveTo(0,-27);ctx.lineTo(12,-5);ctx.lineTo(-12,-5);ctx.closePath();ctx.fill();ctx.strokeStyle='#9b6b37';ctx.beginPath();ctx.arc(11,2,11,-1.5,1.5);ctx.stroke()}else if(k==='priest'){ctx.strokeStyle='#ff7aac';ctx.beginPath();ctx.moveTo(11,-8);ctx.lineTo(11,16);ctx.moveTo(5,-1);ctx.lineTo(17,-1);ctx.stroke()}else if(k==='bomber'){ctx.fillStyle='#1e2530';ctx.beginPath();ctx.arc(11,4,10,0,6.28);ctx.fill();ctx.strokeStyle='#ffbd3d';ctx.beginPath();ctx.moveTo(14,-5);ctx.quadraticCurveTo(22,-15,23,-4);ctx.stroke()}}
}
function cardArtSvg(c){if(c.type==='attr')return mysterySvg('#e4b84c','属性');if(c.type==='rare')return mysterySvg('#b75dff','レア');if(c.type==='buff'){const em={heart:'♥',sword:'⚔',speed:'➤',bomb:'●'}[c.art]||'✦';return `<svg viewBox="0 0 120 120"><defs><radialGradient id="g"><stop stop-color="#ffffff55"/><stop offset="1" stop-color="#ffffff00"/></radialGradient></defs><circle cx="60" cy="60" r="48" fill="url(#g)"/><text x="60" y="80" text-anchor="middle" font-size="64" fill="#fff">${em}</text></svg>`}return unitSvg(c.unit)}
function mysterySvg(color,label){return `<svg viewBox="0 0 120 120"><circle cx="60" cy="60" r="47" fill="${color}33" stroke="${color}" stroke-width="4"/><path d="M42 35h36v50H42z" rx="8" fill="#1b2136" stroke="${color}" stroke-width="3"/><text x="60" y="73" text-anchor="middle" font-size="47" font-weight="900" fill="${color}">?</text><text x="60" y="105" text-anchor="middle" font-size="12" fill="#fff">${label}</text></svg>`}
function unitSvg(id){const t=UNITS[id],color=ROLE_COLORS[t.roleKey];return `<svg viewBox="0 0 120 120"><ellipse cx="60" cy="100" rx="30" ry="9" fill="#0004"/><circle cx="60" cy="49" r="25" fill="#ffd3ae"/><ellipse cx="60" cy="82" rx="23" ry="26" fill="${color}"/><circle cx="51" cy="47" r="3" fill="#292936"/><circle cx="69" cy="47" r="3" fill="#292936"/>${svgEquip(id)}</svg>`}
function svgEquip(id){if(id==='shield')return `<rect x="25" y="63" width="27" height="43" rx="8" fill="#6389c9" stroke="#dbe9ff" stroke-width="4"/><path d="M77 62l18 36" stroke="#f4d06f" stroke-width="6"/>`;if(id==='golem')return `<circle cx="60" cy="48" r="29" fill="#7c897e"/><rect x="24" y="70" width="18" height="37" rx="8" fill="#68736a"/><rect x="78" y="70" width="18" height="37" rx="8" fill="#68736a"/>`;if(id==='knight')return `<path d="M39 45a21 21 0 0142 0v7H39z" fill="#dbe6ef"/><path d="M78 61l17 38" stroke="#f5d36f" stroke-width="7"/>`;if(id==='wolf')return `<path d="M41 34l7-21 12 20M79 34l-7-21-12 20" fill="#59616c"/><ellipse cx="60" cy="83" rx="36" ry="20" fill="#59616c"/>`;if(id==='assassin')return `<path d="M60 18L91 62H29z" fill="#332542"/><path d="M29 97l62-39" stroke="#f6f7ff" stroke-width="6"/>`;if(id==='archer')return `<path d="M89 57c18 14 18 38 0 52" fill="none" stroke="#704c27" stroke-width="6"/><path d="M89 57v52" stroke="#704c27" stroke-width="3"/>`;if(id==='ranger')return `<path d="M60 17L87 59H33z" fill="#4f7650"/><path d="M89 62c15 13 15 33 0 46" fill="none" stroke="#9b6b37" stroke-width="6"/>`;if(id==='priest')return `<path d="M89 58v48M77 71h24" stroke="#ff7aac" stroke-width="7"/>`;if(id==='bomber')return `<circle cx="89" cy="83" r="21" fill="#202632"/><path d="M93 62q16-24 20 1" fill="none" stroke="#ffbd3d" stroke-width="5"/>`;return ''}
function showBanner(text,ms=700){$('centerBanner').textContent=text;$('centerBanner').classList.remove('hidden');setTimeout(()=>$('centerBanner').classList.add('hidden'),ms)}
function gameOver(winner){$('resultPanel').classList.add('hidden');$('gameOverView').classList.remove('hidden');$('gameOverText').textContent=winner==='you'?'YOU WIN!':'YOU LOSE'}
$('nextRoundBtn').onclick=()=>{state.round++;state.battle=null;$('resultPanel').classList.add('hidden');nextDraft()};$('restartBtn').onclick=init;$('againBtn').onclick=init;function wait(ms){return new Promise(r=>setTimeout(r,ms))}function roundRect(x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,r)}init();
