'use strict';
const $=id=>document.getElementById(id);
const canvas=$('battleCanvas'),ctx=canvas.getContext('2d');
const ATTRS={none:{name:'無',icon:'○'},fire:{name:'火',icon:'🔥'},wood:{name:'木',icon:'🌳'},earth:{name:'土',icon:'🪨'},lightning:{name:'雷',icon:'⚡'},water:{name:'水',icon:'💧'}};
const ADV={fire:'wood',wood:'earth',earth:'lightning',lightning:'water',water:'fire'};
const COLORS={tank:'#5ba5ff',knight:'#ffd065',assassin:'#b47cff',archer:'#64dc96',ranger:'#4fd8e8',support:'#ff8bc2',special:'#ff735f'};
const UNITS={
 shield:{name:'盾兵',role:'タンク',lane:'front',count:2,hp:180,atk:17,range:28,speed:22,rate:1.15,art:'shield'},
 golem:{name:'ゴーレム',role:'タンク',lane:'front',count:1,hp:340,atk:31,range:30,speed:12,rate:1.65,art:'golem'},
 knight:{name:'ナイト',role:'ナイト',lane:'mid',count:2,hp:125,atk:34,range:30,speed:28,rate:.95,art:'knight'},
 wolf:{name:'ウルフ',role:'ナイト',lane:'mid',count:3,hp:72,atk:24,range:25,speed:42,rate:.72,art:'wolf'},
 assassin:{name:'アサシン',role:'アサシン',lane:'mid',count:1,hp:82,atk:65,range:25,speed:50,rate:1.05,art:'assassin',backline:true},
 archer:{name:'アーチャー',role:'アーチャー',lane:'back',count:2,hp:68,atk:29,range:130,speed:20,rate:1.15,art:'archer'},
 ranger:{name:'レンジャー',role:'レンジャー',lane:'back',count:2,hp:76,atk:22,range:115,speed:24,rate:.82,art:'ranger'},
 priest:{name:'神官',role:'サポーター',lane:'back',count:1,hp:90,atk:9,range:105,speed:18,rate:1.6,art:'priest',heal:true},
 bomber:{name:'爆弾兵',role:'特攻',lane:'front',count:3,hp:42,atk:100,range:18,speed:55,rate:99,art:'bomber',bomb:true}
};
const unitCards=Object.keys(UNITS).map(id=>({id:'u_'+id,type:'unit',unit:id,name:UNITS[id].name,tag:UNITS[id].role,desc:`${UNITS[id].count}体召喚`,art:UNITS[id].art}));
const buffs=[
 {id:'b_hp',type:'buff',name:'鉄壁訓練',tag:'強化',desc:'全ユニット HP +15%',stat:'hp',value:.15,art:'heart'},
 {id:'b_atk',type:'buff',name:'猛攻訓練',tag:'強化',desc:'全ユニット 攻撃 +15%',stat:'atk',value:.15,art:'sword'},
 {id:'b_spd',type:'buff',name:'迅速訓練',tag:'強化',desc:'全ユニット 攻撃速度 +12%',stat:'rate',value:.12,art:'speed'},
 {id:'b_bomb',type:'buff',name:'大型火薬',tag:'特攻強化',desc:'爆弾兵の爆発 +35%',stat:'bomb',value:.35,art:'bomb'}
];
const attrCards=Object.keys(ATTRS).map(k=>({id:'a_'+k,type:'attr',attr:k,name:k==='none'?'属性解除':ATTRS[k].name+'属性',tag:'属性',desc:k==='none'?'自軍を無属性にする':`自軍を${ATTRS[k].name}属性に上書き`,art:k}));
const rares=[
 {id:'r_life',type:'rare',name:'封印カード',tag:'？？？',desc:'戦闘開始時に開封',effect:'life'},
 {id:'r_swap',type:'rare',name:'封印カード',tag:'？？？',desc:'戦闘開始時に開封',effect:'swap'},
 {id:'r_blank',type:'rare',name:'封印カード',tag:'？？？',desc:'戦闘開始時に開封',effect:'blank'}
];
let state;
function fresh(){return {round:1,you:{life:5,attr:'none',army:[],buff:{hp:0,atk:0,rate:0,bomb:0},rare:[]},npc:{life:5,attr:'none',army:[],buff:{hp:0,atk:0,rate:0,bomb:0},rare:[]},loser:null,pick:0,picksNeeded:3,rerolled:false,timer:null,timeLeft:30,npcPlan:[],battle:null};}
function init(){state=fresh();show('draftView');hide('battleView');hide('gameOverView');nextDraft();}
function show(id){$(id).classList.remove('hidden')}function hide(id){$(id).classList.add('hidden')}
function hearts(n){return '♥'.repeat(Math.max(0,n))+'♡'.repeat(Math.max(0,5-n));}
function updateHud(hidden=true){$('youLife').textContent=hearts(state.you.life);$('npcLife').textContent=hearts(state.npc.life);$('roundNo').textContent=state.round;$('youAttr').textContent=hidden?'？？？':ATTRS[state.you.attr].icon+ATTRS[state.you.attr].name;$('npcAttr').textContent=hidden?'？？？':ATTRS[state.npc.attr].icon+ATTRS[state.npc.attr].name;}
function poolFor(round){let p=[...unitCards];if(round>1)p.push(...buffs);return p;}
function weightedCard(round){const r=Math.random();if(r<.01)return rares[Math.floor(Math.random()*rares.length)];if(r<.07)return attrCards[Math.floor(Math.random()*attrCards.length)];const p=poolFor(round);return p[Math.floor(Math.random()*p.length)];}
function offers(){const out=[];while(out.length<3){const c=weightedCard(state.round);if(!out.some(x=>x.id===c.id))out.push(c)}return out;}
function nextDraft(){clearInterval(state.timer);state.pick=0;state.rerolled=false;state.picksNeeded=state.loser==='you'?4:3;state.npcPlan=[];for(let i=0;i<(state.loser==='npc'?4:3);i++){const os=offers();state.npcPlan.push(chooseNpc(os));}
 updateHud(true);$('phase').textContent='ドラフト';$('draftTitle').textContent=`カード選択 ${state.pick+1}/${state.picksNeeded}`;$('rerollBtn').classList.remove('hidden');renderOffers(offers());startTimer();}
function startTimer(){clearInterval(state.timer);state.timeLeft=30;$('timer').textContent='30';state.timer=setInterval(()=>{state.timeLeft--;$('timer').textContent=state.timeLeft;if(state.timeLeft<=0){clearInterval(state.timer);const cards=[...document.querySelectorAll('.card')];cards[Math.floor(Math.random()*cards.length)]?.click();}},1000)}
function renderOffers(os){const root=$('cards');root.innerHTML='';os.forEach(c=>{const b=document.createElement('button');b.className='card '+(c.type==='rare'?'rare':'');b.innerHTML=`<span class="tag">${c.tag}</span><div class="art">${artSvg(c.art||'mystery')}</div><h3>${c.name}</h3><p>${c.desc}</p>`;b.onclick=()=>pick(c);root.appendChild(b)});$('pickProgress').style.setProperty('--progress',`${state.pick/state.picksNeeded*100}%`)}
function pick(c){clearInterval(state.timer);applyCard(state.you,c);state.pick++;$('pickProgress').style.setProperty('--progress',`${state.pick/state.picksNeeded*100}%`);if(state.pick>=state.picksNeeded){$('rerollBtn').classList.add('hidden');setTimeout(beginBattle,180);return}$('draftTitle').textContent=`カード選択 ${state.pick+1}/${state.picksNeeded}`;renderOffers(offers());startTimer();}
function applyCard(p,c){if(c.type==='unit')p.army.push(c.unit);if(c.type==='buff')p.buff[c.stat]+=c.value;if(c.type==='attr')p.attr=c.attr;if(c.type==='rare')p.rare.push(c.effect)}
function chooseNpc(os){return [...os].sort((a,b)=>scoreNpc(b)-scoreNpc(a))[0]}
function scoreNpc(c){if(c.type==='rare')return 88;if(c.type==='unit'){let s=50;if(state.npc.army.length<3)s+=25;if(c.unit==='shield'||c.unit==='golem')s+=8;return s+Math.random()*12}if(c.type==='buff')return state.npc.army.length?58+Math.random()*14:15;if(c.type==='attr')return 42+Math.random()*20;return 20}
$('rerollBtn').onclick=()=>{if(state.rerolled)return;state.rerolled=true;$('rerollBtn').classList.add('hidden');renderOffers(offers());startTimer()};
async function revealRares(){for(const side of ['npc','you']){while(state[side].rare.length){const e=state[side].rare.shift();show('rareOverlay');$('rareResult').textContent='';await wait(500);let text='';if(e==='life'){state[side].life++;text=`${side==='you'?'YOU':'NPC'}：ライフ +1`;updateHud(true)}else if(e==='swap'){const other=side==='you'?'npc':'you';if(state[side].army.length&&state[other].army.length){const ai=Math.floor(Math.random()*state[side].army.length),bi=Math.floor(Math.random()*state[other].army.length);[state[side].army[ai],state[other].army[bi]]=[state[other].army[bi],state[side].army[ai]];text='両軍のユニットが1体入れ替わった'}else text='入れ替えるユニットがいなかった'}else{text='……何も起こらなかった'}$('rareResult').textContent=text;await wait(1100);hide('rareOverlay')}}}
async function beginBattle(){clearInterval(state.timer);state.npcPlan.forEach(c=>applyCard(state.npc,c));hide('draftView');show('battleView');$('nextRoundBtn').classList.add('hidden');$('battleLog').textContent='';$('phase').textContent='開封';await revealRares();$('phase').textContent='属性公開';updateHud(false);$('attributeReveal').textContent=`NPC ${ATTRS[state.npc.attr].icon}  VS  ${ATTRS[state.you.attr].icon} YOU`;await wait(900);startBattle();}
function makeFighters(side){const p=state[side],dir=side==='you'?-1:1;const laneBase=side==='you'?{front:540,mid:610,back:665}:{front:160,mid:90,back:35};let laneIndex={front:0,mid:0,back:0},arr=[];for(const id of p.army){const t=UNITS[id];for(let i=0;i<t.count;i++){const idx=laneIndex[t.lane]++;const x=75+(idx%5)*68+(Math.floor(idx/5)%2)*18;const y=laneBase[t.lane]+Math.floor(idx/5)*28*dir;arr.push({id:Math.random(),side,type:id,x,y,vx:0,vy:0,hp:t.hp*(1+p.buff.hp),maxHp:t.hp*(1+p.buff.hp),atk:t.atk*(1+p.buff.atk),range:t.range,speed:t.speed,rate:Math.max(.35,t.rate*(1-p.buff.rate)),cool:Math.random(),alive:true,lane:t.lane,role:t.role,backline:t.backline,heal:t.heal,bomb:t.bomb,bombMult:1+p.buff.bomb,target:null,flash:0})}}return arr}
function startBattle(){state.battle={units:[...makeFighters('npc'),...makeFighters('you')],last:performance.now(),done:false,particles:[]};requestAnimationFrame(loop)}
function loop(now){if(!state.battle||state.battle.done)return;const dt=Math.min(.035,(now-state.battle.last)/1000);state.battle.last=now;updateBattle(dt);drawBattle();if(!state.battle.done)requestAnimationFrame(loop)}
function attrMult(a,b){return ADV[a]===b?1.25:ADV[b]===a?.8:1}
function nearest(u,enemies){if(u.backline){const backs=enemies.filter(e=>e.lane==='back');if(backs.length)enemies=backs}let best=null,bd=1e9;for(const e of enemies){const d=Math.hypot(e.x-u.x,e.y-u.y);if(d<bd){bd=d;best=e}}return best}
function damage(att,target,amount){const am=attrMult(state[att.side].attr,state[target.side].attr);target.hp-=amount*am;target.flash=.13;state.battle.particles.push({x:target.x,y:target.y,text:'-'+Math.round(amount*am),life:.75});if(target.hp<=0){target.alive=false;if(target.bomb)explode(target)}}
function explode(u){state.battle.particles.push({x:u.x,y:u.y,text:'BOOM!',life:1,big:true});for(const e of state.battle.units.filter(x=>x.alive&&x.side!==u.side&&Math.hypot(x.x-u.x,x.y-u.y)<95))damage(u,e,u.atk*u.bombMult)}
function updateBattle(dt){const units=state.battle.units;for(const u of units){if(!u.alive)continue;u.cool-=dt;u.flash=Math.max(0,u.flash-dt);const foes=units.filter(e=>e.alive&&e.side!==u.side);if(!foes.length){finishBattle(u.side);return}if(u.heal&&u.cool<=0){const allies=units.filter(e=>e.alive&&e.side===u.side&&e.hp<e.maxHp);if(allies.length){const a=allies.sort((a,b)=>a.hp/a.maxHp-b.hp/b.maxHp)[0];a.hp=Math.min(a.maxHp,a.hp+22);state.battle.particles.push({x:a.x,y:a.y,text:'+22',life:.7,heal:true});u.cool=u.rate;continue}}
 if(!u.target||!u.target.alive)u.target=nearest(u,foes);const t=u.target;if(!t)continue;const dx=t.x-u.x,dy=t.y-u.y,d=Math.hypot(dx,dy)||1;if(d<=u.range){u.vx*=.72;u.vy*=.72;if(u.cool<=0){if(u.bomb){u.alive=false;explode(u)}else damage(u,t,u.atk);u.cool=u.rate}}else{let desired=u.speed;if(u.lane==='back'&&d<70)desired=-u.speed*.7;const tx=dx/d*desired,ty=dy/d*desired;u.vx+=(tx-u.vx)*Math.min(1,dt*7);u.vy+=(ty-u.vy)*Math.min(1,dt*7);u.x+=u.vx*dt;u.y+=u.vy*dt;u.x=Math.max(26,Math.min(394,u.x));u.y=Math.max(25,Math.min(675,u.y))}}
 state.battle.particles.forEach(p=>p.life-=dt);state.battle.particles=state.battle.particles.filter(p=>p.life>0)}
function finishBattle(winner){state.battle.done=true;const loser=winner==='you'?'npc':'you';state[loser].life--;state.loser=loser;$('battleLog').textContent=`${winner==='you'?'YOU':'NPC'} がラウンド勝利\n${loser==='you'?'YOU':'NPC'} のライフ -1`;updateHud(false);if(state[loser].life<=0){setTimeout(()=>gameOver(winner),700)}else{$('nextRoundBtn').classList.remove('hidden')}}
function roleColor(role){return ({'タンク':COLORS.tank,'特攻':COLORS.special,'アサシン':COLORS.assassin,'アーチャー':COLORS.archer,'ナイト':COLORS.knight,'レンジャー':COLORS.ranger,'サポーター':COLORS.support})[role]||'#fff'}
function drawBattle(){ctx.clearRect(0,0,420,700);const g=ctx.createLinearGradient(0,0,0,700);g.addColorStop(0,'#462b38');g.addColorStop(.49,'#202944');g.addColorStop(.51,'#202944');g.addColorStop(1,'#25394a');ctx.fillStyle=g;ctx.fillRect(0,0,420,700);ctx.strokeStyle='#ffffff22';ctx.setLineDash([8,8]);ctx.beginPath();ctx.moveTo(0,350);ctx.lineTo(420,350);ctx.stroke();ctx.setLineDash([]);for(const u of state.battle.units){if(!u.alive)continue;drawUnit(u)}for(const p of state.battle.particles){ctx.globalAlpha=Math.min(1,p.life*2);ctx.fillStyle=p.heal?'#75ff9c':p.big?'#ffd04d':'#fff';ctx.font=`bold ${p.big?25:13}px sans-serif`;ctx.textAlign='center';ctx.fillText(p.text,p.x,p.y-p.life*22);ctx.globalAlpha=1}}
function drawUnit(u){const t=UNITS[u.type];ctx.save();ctx.translate(u.x,u.y);ctx.fillStyle=u.flash?'#fff':roleColor(u.role);ctx.strokeStyle=u.side==='you'?'#6ee7ff':'#ff8099';ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,0,14,0,Math.PI*2);ctx.fill();ctx.stroke();drawIcon(ctx,t.art,0,0,22);ctx.fillStyle='#10131f';ctx.fillRect(-17,-23,34,5);ctx.fillStyle=u.hp/u.maxHp>.5?'#5dff86':u.hp/u.maxHp>.25?'#ffd85d':'#ff566f';ctx.fillRect(-17,-23,34*Math.max(0,u.hp/u.maxHp),5);ctx.restore()}
function drawIcon(c,art,x,y,s){c.save();c.translate(x,y);c.strokeStyle='#111827';c.fillStyle='#f7f3e8';c.lineWidth=2;if(art==='shield'){c.fillRect(-8,-10,12,18);c.strokeRect(-8,-10,12,18);c.beginPath();c.moveTo(5,-10);c.lineTo(10,9);c.stroke()}else if(art==='golem'){c.fillRect(-9,-10,18,19);c.fillStyle='#667085';c.fillRect(-12,-5,5,13);c.fillRect(7,-5,5,13)}else if(art==='knight'){c.beginPath();c.arc(0,-4,7,0,Math.PI*2);c.fill();c.beginPath();c.moveTo(5,2);c.lineTo(11,-10);c.stroke()}else if(art==='archer'||art==='ranger'){c.beginPath();c.arc(-2,-3,6,0,Math.PI*2);c.fill();c.beginPath();c.arc(5,0,8,-Math.PI/2,Math.PI/2);c.stroke();c.beginPath();c.moveTo(5,-8);c.lineTo(5,8);c.stroke()}else if(art==='assassin'){c.fillStyle='#2a203c';c.beginPath();c.moveTo(0,-11);c.lineTo(9,7);c.lineTo(-9,7);c.closePath();c.fill();c.strokeStyle='#fff';c.beginPath();c.moveTo(-6,4);c.lineTo(7,-6);c.stroke()}else if(art==='wolf'){c.beginPath();c.arc(0,0,8,0,Math.PI*2);c.fill();c.beginPath();c.moveTo(-7,-5);c.lineTo(-6,-12);c.lineTo(-1,-7);c.moveTo(7,-5);c.lineTo(6,-12);c.lineTo(1,-7);c.stroke()}else if(art==='priest'){c.beginPath();c.arc(0,-5,6,0,Math.PI*2);c.fill();c.strokeStyle='#ff4f9a';c.beginPath();c.moveTo(0,2);c.lineTo(0,11);c.moveTo(-5,6);c.lineTo(5,6);c.stroke()}else if(art==='bomber'){c.fillStyle='#222';c.beginPath();c.arc(0,1,9,0,Math.PI*2);c.fill();c.strokeStyle='#ffb52e';c.beginPath();c.moveTo(4,-7);c.quadraticCurveTo(10,-14,12,-7);c.stroke()}c.restore()}
function artSvg(type){const emoji={heart:'❤️',sword:'⚔️',speed:'💨',bomb:'💣',fire:'🔥',wood:'🌳',earth:'🪨',lightning:'⚡',water:'💧',none:'○',mystery:'❔'}[type];if(emoji)return `<div style="font-size:70px">${emoji}</div>`;const map={shield:'🛡️',golem:'🗿',knight:'⚔️',wolf:'🐺',assassin:'🥷',archer:'🏹',ranger:'🪃',priest:'✨',bomber:'💣'};return `<svg viewBox="0 0 120 120" aria-label="${type}"><circle cx="60" cy="58" r="45" fill="#ffffff18"/><text x="60" y="79" text-anchor="middle" font-size="58">${map[type]||'❔'}</text></svg>`}
function gameOver(w){hide('battleView');show('gameOverView');$('gameOverText').textContent=w==='you'?'YOU WIN!':'YOU LOSE';}
$('nextRoundBtn').onclick=()=>{state.round++;hide('battleView');show('draftView');nextDraft()};$('restartBtn').onclick=init;$('againBtn').onclick=init;function wait(ms){return new Promise(r=>setTimeout(r,ms))}init();
